- name : loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages 
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql 
    - nginx  

  - name: install packages 
    ansible.builtin.package:
      name: "{{ item }}"
      state: absent  
    loop:
    - mysql 
    - nginx   