- name: ansible cmd vs shell
  hosts: local
  connection: local
  tasks:
  - name: shell module test 
    ansible.builtin.shell: cat /etc/passwd | grep root 
    register: users_output

  - name: print users_output
    ansible.builtin.debug:
      msg: "{{ users_output }}"

  - name: shell module test 
    ansible.builtin.shell: ls -ltr > files.txt
    register: files_output

  - name: print files_output
    ansible.builtin.debug:
      msg: "{{ files_output }}"  