#task level
- name: task level variables
  hosts: local
  connection: local
  vars:
   Course: "devops with aws"
   Duration: "140 hrs"
   Trainer: "siva"
  tasks:
  - name: print variables
    vars: 
     Course: ansible
    ansible.builtin.debug:
      msg: "Course is {{Course}}, Trainer is {{Trainer}}